/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(chameleon.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(63c602d1543da8e25e155b358b1ceeaa)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/ihd/chameleon.h>
// pydoc.h is automatically generated in the build directory
#include <chameleon_pydoc.h>

void bind_chameleon(py::module& m)
{

    using chameleon    = gr::ihd::chameleon;


    py::class_<chameleon, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<chameleon>>(m, "chameleon", D(chameleon))

        .def(py::init(&chameleon::make),
           D(chameleon,make)
        )
        



        ;




}








