/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(chameleon_fft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7f17c039625727156151b72674274e13)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/chameleon/chameleon_fft.h>
// pydoc.h is automatically generated in the build directory
#include <chameleon_fft_pydoc.h>

void bind_chameleon_fft(py::module& m)
{

    using chameleon_fft    = gr::chameleon::chameleon_fft;


    py::class_<chameleon_fft, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<chameleon_fft>>(m, "chameleon_fft", D(chameleon_fft))

        .def(py::init(&chameleon_fft::make),
           D(chameleon_fft,make)
        )
        



        ;




}








