//
// Created by jmeyers on 6/26/24.
//

#ifndef CHAMELEON_FW_COMMON_H
#define CHAMELEON_FW_COMMON_H

#define CHAMELEON_FW_COMMS_UDP_PORT 49152
#define CHAMELEON_VITA_UDP_PORT 49153
#define CHAMELEON_FPGA_PROG_UDP_PORT 49157
#define CHAMELEON_FPGA_READ_UDP_PORT 49159

#define CHAMELEON_FW_COMMS_IPADDR "10.75.42.8"

#endif //CHAMELEON_FW_COMMON_H
